from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from .source import Source  # Import the Source model
from pydantic import field_serializer
from typing import Union
from datetime import date

class AgentResponse(BaseModel):
    """
    Represents the response generated by the RAG agent, including content and source information.
    """
    content: str = Field(..., description="The agent's response text")
    sources: Optional[List[Source]] = Field(None, description="List of source documents used", max_length=10)
    query: str = Field(..., description="The original query that generated this response")
    agentId: str = Field(..., description="ID of the agent that generated the response")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the response was generated")

    @field_serializer('timestamp')
    def serialize_timestamp(self, dt: datetime) -> str:
        return dt.isoformat()

    def model_post_init(self, __context):
        """Validate that content is non-empty after initialization."""
        if not self.content or not self.content.strip():
            raise ValueError('Content must be non-empty')

        if self.sources is not None:
            # Validate that query matches the original query sent
            # (This would be checked during response creation)
            pass